import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { unstable_ViewTransition as ViewTransition } from 'react';
import Link from "next/link";
import Image from "next/image";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const robotoFont = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}


export default function RootLayout({ children, params }: Readonly<{ children: React.ReactNode, params: { slug?: string }}>) {
  return (
    <html lang="en" data-theme="dark">
      <body className={`${robotoFont.variable} antialiased dark:bg-[#292929]`}>
        <Header />
        <ViewTransition key={params?.slug || 'root'}>
          {children}
        </ViewTransition>
      </body>
    </html>
  )
}
